-- MySQL Script generated by MySQL Workbench
-- 11/02/15 22:13:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zmarket4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zmarket4` DEFAULT CHARACTER SET utf8 ;
USE `zmarket4` ;

-- -----------------------------------------------------
-- Table `zmarket4`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zmarket4`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `category` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `price` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
