-- MySQL Script generated by MySQL Workbench
-- 11/03/15 16:41:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zmarket4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zmarket4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zmarket4` DEFAULT CHARACTER SET utf8 ;
USE `zmarket4` ;

-- -----------------------------------------------------
-- Table `zmarket4`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zmarket4`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zmarket4`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zmarket4`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `price` INT(11) NOT NULL COMMENT '',
  `category_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `category_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_product_category_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_category`
  FOREIGN KEY (`category_id`)
  REFERENCES `zmarket4`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  AUTO_INCREMENT = 10
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
